ruby/config/routes.rb
require 'domain_constraint'
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints DomainConstraint.new('career', 'career-source', 'career-dev') do
    root to: 'career#index'
    get '/social',         to: 'career#social'
    get '/school',         to: 'career#school'
    get '/position/:id',   to: 'career#position', as: :position
  end

  constraints DomainConstraint.new('blog', 'blog-source', 'blog-dev') do
    root to: 'blog#index'
    get '/archives/all',                to: 'blog#all'
    get '/archives/:id',                to: 'blog#archives', as: :archives
    get '/archives/author/:author',     to: 'blog#author',   as: :archives_author
    get '/archives/category/:category', to: 'blog#category', as: :archives_category
  end

  scope "(:locale)", locale: /en/ do
    root to: 'welcome#index'
    get '/products/kodo',                          to: 'products#kodo'
    get '/products/kodo/goglobal',                 to: 'products#kodo_goglobal'
    get '/products/pili',                          to: 'products#pili'
    get '/products/sdk',                           to: 'products#sdk'
    get '/products/rtn',                           to: 'products#rtn'
    get '/products/pandora',                       to: 'products#pandora'
    get '/products/insight',                       to: 'products#insight'
    get '/products/express',                       to: 'products#express'
    get '/products/censor',                        to: 'products#censor'
    get '/products/fusion',                        to: 'products#fusion'
    get '/products/qcdn',                          to: 'products#qcdn'
    get '/products/dora',                          to: 'products#dora'
    get '/products/kirk',                          to: 'products#kirk'
    get '/products/vance',                         to: 'products#vance'
    get '/products/atlab',                         to: 'products#atlab'
    get '/products/plsv',                          to: 'products#plsv'
    get '/products/vcs',                           to: 'products#vcs'
    get '/products/player',                        to: 'products#player'
    get '/products/newmedia',                      to: 'products#newmedia'
    get '/products/newmedia/playout',              to: 'products#playout'
    get '/products/newmedia/mam',                  to: 'products#mam'
    get '/products/newmedia/convergence',          to: 'products#convergence'
    get '/products/newmedia/cms',                  to: 'products#cms'
    get '/products/newmedia/operation',            to: 'products#operation'
    get '/products/newmedia/live',                 to: 'products#live'
    # 超级分辨率下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/resolution',           to: 'products#resolution'
    get '/products/newmedia/demolition',           to: 'products#demolition'
    # 业务微服务引擎下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/microservices',        to: 'products#microservices'
    get '/products/newmedia/editor',               to: 'products#editor'
    # 数据可视化下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/visualization',        to: 'products#visualization'
    get '/products/newmedia/interact',             to: 'products#interact'
    get '/products/newmedia/auditor',              to: 'products#auditor'
    get '/products/newmedia/copyright',            to: 'products#copyright'
    get '/products/pili/livequiz',                 to: 'products#livequiz'
    get '/products/qavs',                          to: 'products#qavs'
    get '/products/qvm',                           to: 'products#qvm'
    get '/products/qvm/partner',                   to: 'products#qvm_partner'
    get '/products/qvm-company',                   to: 'products#qvm_company'
    get '/products/edu',                           to: 'products#edu'
    get '/products/ess',                           to: 'products#ess'
    get '/products/snow',                          to: 'products#snow'
    get '/products/ecs',                           to: 'products#ecs'
    get '/products/private-cloud-kodo',            to: 'products#kodoprivate'
    get '/products/private-cloud-kodo/company',    to: 'products#kodoprivate_company'
    get '/products/linking',                       to: 'products#linking'
    get '/products/sms',                           to: 'products#sms'
    get '/products/svesdk',                        to: 'products#svesdk'

    # 推广结束，屏蔽 qvmfeeds 和 censorfeeds 的路由
    # https://jira.qiniu.io/browse/BO-5919
    # qvm 广告推广页
    # get '/products/qvmfeeds',       to: 'products#qvmfeeds'
    # censor 广告推广页
    # get '/products/censorfeeds',    to: 'products#censorfeeds'

    # censor 新增的两个页面，用于关键词排名，只增加路由不新增入口
    # https://jira.qiniu.io/browse/BO-5767
    get '/products/censor/photo',   to: 'products#censor_photo'
    get '/products/censor/video',   to: 'products#censor_video'

    get '/contact',                to: 'welcome#contact'
    get '/solutions',              to: 'welcome#solution'
    get '/news',                   to: 'welcome#news'
    get '/product_news',           to: 'welcome#product_news'
    get '/welfares',               to: 'welcome#welfares'
    get '/company',                to: 'welcome#company'
    get '/case',                   to: 'welcome#case'
    get '/user-agreement',         to: 'welcome#user_agreement'
    get '/sdk-agreement',          to: 'welcome#sdk_agreement'
    get '/sla-kodo',               to: 'welcome#sla_kodo'
    get '/sla-kodo-old',           to: 'welcome#sla_kodo_old'
    get '/sla-kodo-new',           to: 'welcome#sla_kodo_new'
    get '/sla-fusion',             to: 'welcome#sla_fusion'
    get '/sla-fusion-old',         to: 'welcome#sla_fusion_old'
    get '/sla-fusion-new',         to: 'welcome#sla_fusion_new'
    get '/sla-pili',               to: 'welcome#sla_pili'
    get '/sla-dora',               to: 'welcome#sla_dora'
    get '/sla-sms',                to: 'welcome#sla_sms'
    get '/sla-qvm',                to: 'welcome#sla_qvm'
    get '/privacy-right',          to: 'welcome#privacy_right'
    # get '/goglobal',               to: 'welcome#goglobal'
    # get '/alaccelerator',          to: 'welcome#alaccelerator'
    get '/cdnprice2018',           to: 'welcome#cdnprice2018'
    get '/invite',                 to: 'welcome#invite'
    get '/ssl',                    to: 'welcome#ssl'
    get '/partner',                to: 'welcome#partner'

    get '/solutions/kodoe',                        to: 'solutions#kodoe'

    resources :resources, only: [] do
      collection do
        get 'plup'
      end
    end

    # userinfo
    get '/userinfo', to: 'userinfo#userinfo'

    resources 'events', only: [:index] do
      collection do
        get 'tech_online', 'ecug', 'niushow', 'arch', 'ecugcon', 'free', 'qvm1rmb', 'qvm0rmb', 'double11', 'qvm2for3', 'activity'
      end
    end

    # 获取动态 banner
    get '/banner/dynamic', to: 'welcome#get_dynamic_banner'
    # 获取动态广告位
    get '/advert/dynamic', to: 'welcome#get_dynamic_advert'

    # 1024 活动页定位到 events#event1024
    get '/events/1024event', to: 'events#event1024'
    # 限时 cdn 流量包活动页面路由
    get '/events/cdn-package', to: 'events#cdn_package'
    # cdn + 短视频活动页面路由
    get '/events/fusion-package', to: 'events#fusion_package'
    # dora 转码时长包活动
    get '/events/dora-package', to: 'events#dora_package'
    # qvm 燃情一夏活动
    get '/events/qvmsumsale', to: 'events#qvmsumsale'
    # dora 促销活动
    get '/events/dora-avsmart', to: 'events#dora_avsmart'
    # qvmsumsale 10 点开抢限制
    get '/events/qvmsumsale/is_start', to: 'events#qvmsumsale_is_start'
    # 2019 年 618 活动
    # https://jira.qiniu.io/browse/BO-7519
    get '/events/2019618', to: 'events#big_promotion'
    # 2019 年 618 活动是否结束
    get '/events/2019618/is_end', to: 'events#is_big_promotion_end'
    # 2019 年 1024 活动
    # https://jira.qiniu.io/browse/BO-9137
    get '/events/20191024', to: 'events#zelda'
    # 2019 年 1024 活动是否结束
    get '/events/20191024/is_end', to: 'events#is_zelda_end'
    # 2019 年 1111 活动
    get '/events/20191111', to: 'events#double11_2019'
    # 2019 年 1111 活动是否结束
    get '/events/20191111/is_end', to: 'events#is_double11_2019_end'
    # 2019 年 1111 活动 dora 领券
    post '/events/20191111/dora/voucher', to: 'events#double11_2019_dora_voucher'
    # 2019 年 1212 活动
    get '/events/20191212', to: 'events#double12_2019'
    # 2019 年 1212 活动是否结束
    get '/events/20191212/is_end', to: 'events#is_double12_2019_end'
    # 2019 年 1212 活动组合包预约功能
    get '/events/20191212/combo/order', to: 'events#double12_2019_combo_order'
    # 购买套餐包
    post '/events/package/buy', to: 'events#package_buy'
    # 2020 年春季采购活动
    get '/events/20200316', to: 'events#spring_sale'
    # 2020 年春季采购活动是否结束
    get '/events/20200316/is_end', to: 'events#is_spring_sale_end'
    # 获取分享链接
    get '/get_share_link', to: 'events#get_share_link'
    # 获取用户邀请信息
    get '/get_invited_info', to: 'events#get_invited_info'
    # 获取 1024 活动是否过期
    get '/get_expired', to: 'events#get_expired'
    # 创建 1024 活动抽奖资格
    post '/event1024_create_award', to: 'events#event1024_create_award'

    # 抗击 2019-nCoV 活动
    get '/events/fighting-2019-ncov', to: 'events#fighting_ncov'

    # img_censor
    post '/img_censor', to: 'products#img_censor'

    # video_censor
    post '/video_censor', to: 'products#video_censor'

    # 根据 jobID 获取视频审核结果
    post '/video_censor_result', to: 'products#video_censor_result'

    # 获取 censor 产品页 今日审核总量 和 今日已封禁违规内容 数据
    get '/censor_quantity_data', to: 'products#censor_quantity_data'

    # qvm
    post "/qvm/user/action", to: 'products#report_user_action'

    # get_heat
    get '/get_heat', to: 'events#get_heat'

    resources 'prices', only: [:index]
    # https://jira.qiniu.io/browse/BO-6267
    # caculator 路由改为 calculator, caculator_qvm 路由改为 calculator_qvm
    # 为了防止现有的路由 404，因此不关闭现有路由

ruby/app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="keywords" content="qiniu" />
    <meta name="description" content="qiniu.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <title><%= @title && "#{@title} - " -%>七牛云</title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="https://cdn.staticfile.org/highlight.js/9.8.0/styles/atom-one-light.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script>
      (function(para) {
        var p = para.sdk_url, n = para.name, w = window, d = document, s = 'script',x = null,y = null;
        if(typeof(w['sensorsDataAnalytic201505']) !== 'undefined') {
          return false;
        }
        w['sensorsDataAnalytic201505'] = n;
        w[n] = w[n] || function(a) {return function() {(w[n]._q = w[n]._q || []).push([a, arguments]);}};
        var ifs = ['track','quick','register','registerPage','registerOnce','trackSignup', 'trackAbtest', 'setProfile','setOnceProfile','appendProfile', 'incrementProfile', 'deleteProfile', 'unsetProfile', 'identify','login','logout','trackLink','clearAllRegister','getAppStatus'];
        for (var i = 0; i < ifs.length; i++) {
          w[n][ifs[i]] = w[n].call(null, ifs[i]);
        }
        if (!w[n]._t) {
          x = d.createElement(s), y = d.getElementsByTagName(s)[0];
          x.async = 1;
          x.src = p;
          x.setAttribute('charset','UTF-8');
          w[n].para = para;
          y.parentNode.insertBefore(x, y);
        }
      })({
        sdk_url: 'https://static.sensorsdata.cn/sdk/1.13.14/sensorsdata.min.js',
        heatmap_url: 'https://static.sensorsdata.cn/sdk/1.13.14/heatmap.min.js',
        name: 'sensors',
        server_url: 'https://sensors.qiniu.com/sa?project=default',
        heatmap: {},
        show_log: false
      });
      sensors.quick('autoTrack');
    </script>
  </head>

  <body class="<%= controller_name -%>-page <%= "#{controller_name}-page-#{action_name}" -%>">
    <!--[if lt IE 10]>
      <p class="browsehappy">您正在使用 <strong>旧浏览器</strong> . 为了更好的体验，请 <a href="http://browsehappy.com/">更新</a> 您的浏览器.</p>
    <![endif]-->

    <nav class="navbar navbar-default nav-bg" id="navbar">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to content_tag(:span, nil, class: "glyphicon glyphicon-align-justify"), "javascript:;", class: "sidebar-toggle visible-xs"%>
          <%= link_to image_tag("logo-qiniu.png", width: 40), "/", class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "官网", "http://www.qiniu.com/", target: "_blank" -%></li>
            <li><%= link_to "开发者平台", Rails.configuration.portal_host, target: "_blank" -%></li>
            <li><%= link_to "开发者中心", "http://developer.qiniu.com/", target: "_blank" -%></li>
            <li><%= link_to "问答社区", "http://segmentfault.com/qiniu", target: "_blank" -%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right navbar-nav-mobile">
            <li class="dropdown hidden userinfo <%= I18n.t("views.language") != 'zh' ? 'd-none' : '' %>" id="user-dropdown">
              <a href="#" class="dropdown-toggle dropdown-toggle-mobile user-email" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
              <ul class="dropdown-menu user-menu">
                <li><a href="<%= signout_url() -%>" class="text-sub">退出当前帐号</a></li>
              </ul>
            </li>
            <li class="need-signin <%= I18n.t("views.language") != 'zh' ? 'd-none' : '' %>">
              <div class="actions">
                <a href="<%= signin_url('blog', '') %>" class="btn btn-hollow">登录</a>
                <a href="<%= signup_url() %>" target="_blank" class="btn btn-primary">注册有礼</a>
              </div>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>

    <footer class="form-footer">
      <div class="container">
        <div class="links blog-footer-links">
          <ul>
            <li><div class="copyright">© <%= Time.now.strftime "%Y" -%> 七牛云</div></li>
            <li><a href="/user-agreement">用户协议</a></li>
            <li><a href="/privacy-right">隐私权政策</a></li>
            <% if false -%>
            <li><a href="/sla-kodo">SLA</a></li>
            <% end -%>
          </ul>
          <div class="icp">
              <a class="out_link" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=31011502000961" target="_blank" rel="nofollow"><span class="icon icon-aq">沪公网安备 31011502000961 号</span></a>
              <a class="out_link" href="http://www.beian.miit.gov.cn/" target="_blank" rel="nofollow"><span>沪 ICP 备 11037377 号-5</span></a>
          </div>
        </div>
        <div class="contact-links">
          <div class="sns">
            <a class="weixin" href="javascript:;"></a>
            <div class="popover fade top in" id="wexin-qrcode-popover">
              <div class="arrow"></div>
              <div class="popover-content"><%= image_tag "weixin-qrcode.png", width: 140 -%></div>
            </div>
            <a class="github" href="https://github.com/qiniu" target="_blank"></a>
            <a class="weibo" href="http://weibo.com/qiniutek" target="_blank"></a>
          </div>
        </div>
      </div>
    </footer>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-88944261-4"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-88944261-4');
    </script>
    <script>
      var _hmt = _hmt || [];
      (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?204fcf6777f8efa834fe7c45a2336bf1";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();
    </script>
    <script>
      (function() {
        var hostname = window.location.hostname;
        var domain = hostname.split('.').slice(-2).join('.');
        if (domain && domain !== 'localhost' && domain.indexOf('qiniu.io') < 0) {
          var bp = document.createElement('script');
          var curProtocol = window.location.protocol.split(':')[0];
          if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
          } else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
          }
          var s = document.getElementsByTagName("script")[0];
          s.parentNode.insertBefore(bp, s);
        }
      })();
    </script>
    <script type="text/javascript" src="https://cdn.staticfile.org/highlight.js/9.8.0/highlight.min.js"></script>
    <script type="text/javascript" src="https://cdn.staticfile.org/highlight.js/9.8.0/languages/go.min.js"></script>
  </body>
</html>

ruby/app/views/layouts/career.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="keywords" content="qiniu" />
    <meta name="description" content="qiniu.com">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    <title><%= @title && "#{@title} - " -%>七牛云</title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script>
      (function(para) {
        var p = para.sdk_url, n = para.name, w = window, d = document, s = 'script',x = null,y = null;
        if(typeof(w['sensorsDataAnalytic201505']) !== 'undefined') {
          return false;
        }
        w['sensorsDataAnalytic201505'] = n;
        w[n] = w[n] || function(a) {return function() {(w[n]._q = w[n]._q || []).push([a, arguments]);}};
        var ifs = ['track','quick','register','registerPage','registerOnce','trackSignup', 'trackAbtest', 'setProfile','setOnceProfile','appendProfile', 'incrementProfile', 'deleteProfile', 'unsetProfile', 'identify','login','logout','trackLink','clearAllRegister','getAppStatus'];
        for (var i = 0; i < ifs.length; i++) {
          w[n][ifs[i]] = w[n].call(null, ifs[i]);
        }
        if (!w[n]._t) {
          x = d.createElement(s), y = d.getElementsByTagName(s)[0];
          x.async = 1;
          x.src = p;
          x.setAttribute('charset','UTF-8');
          w[n].para = para;
          y.parentNode.insertBefore(x, y);
        }
      })({
        sdk_url: 'https://static.sensorsdata.cn/sdk/1.13.14/sensorsdata.min.js',
        heatmap_url: 'https://static.sensorsdata.cn/sdk/1.13.14/heatmap.min.js',
        name: 'sensors',
        server_url: 'https://sensors.qiniu.com/sa?project=default',
        heatmap: {},
        show_log: false
      });
      sensors.quick('autoTrack');
    </script>
  </head>

  <body class="<%= controller_name -%>-page <%= "#{controller_name}-page-#{action_name}" -%>">
    <!--[if lt IE 10]>
      <p class="browsehappy">您正在使用 <strong>旧浏览器</strong> . 为了更好的体验，请 <a href="http://browsehappy.com/">更新</a> 您的浏览器.</p>
    <![endif]-->

    <nav class="navbar navbar-default nav-bg" id="navbar">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("logo-qiniu.png", width: 40) + content_tag( :span, '七牛招聘', class: "navbar-brand-text"), "/", class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "人在七牛", "/" -%></li>
            <li><%= link_to "认识七牛", "https://www.qiniu.com/company", target: "_blank" -%></li>
            <li><%= link_to "社会招聘", social_path -%></li>
            <li><%= link_to "校园招聘", school_path -%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right navbar-nav-mobile">
            <li class="dropdown hidden userinfo <%= I18n.t("views.language") != 'zh' ? 'd-none' : '' %>" id="user-dropdown">
              <a href="#" class="dropdown-toggle dropdown-toggle-mobile user-email" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"></a>
              <ul class="dropdown-menu user-menu">
                <li><a href="<%= signout_url() -%>" class="text-sub">退出当前帐号</a></li>
              </ul>
            </li>
            <li class="need-signin <%= I18n.t("views.language") != 'zh' ? 'd-none' : '' %>">
              <div class="actions">
                <a href="<%= signin_url('career', '') %>" class="btn btn-hollow">登录</a>
                <a href="<%= signup_url() %>" target="_blank" class="btn btn-primary">注册有礼</a>
              </div>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>

    <footer class="form-footer">
      <div class="container">
        <div class="links career-footer-links">
          <ul>
            <li><div class="copyright">© <%= Time.now.strftime "%Y" -%> 七牛云</div></li>
            <li><a href="/user-agreement">用户协议</a></li>
            <li><a href="/privacy-right">隐私权政策</a></li>
            <% if false -%>
            <li><a href="/sla-kodo">SLA</a></li>
            <% end -%>
          </ul>
          <div class="icp">
              <a class="out_link" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=31011502000961" target="_blank" rel="nofollow"><span class="icon icon-aq">沪公网安备 31011502000961 号</span></a>
              <a class="out_link" href="http://www.beian.miit.gov.cn/" target="_blank" rel="nofollow"><span>沪 ICP 备 11037377 号-5</span></a>
          </div>
        </div>
        <div class="contact-links">
          <div class="sns">
            <a class="weixin" href="javascript:;"></a>
            <div class="popover fade top in" id="wexin-qrcode-popover">
              <div class="arrow"></div>
              <div class="popover-content"><%= image_tag "weixin-qrcode.png", width: 140 -%></div>
            </div>
            <a class="github" href="https://github.com/qiniu" target="_blank"></a>
            <a class="weibo" href="http://weibo.com/qiniutek" target="_blank"></a>
          </div>
        </div>
      </div>
    </footer>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-88944261-3"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-88944261-3');
    </script>
    <script>
      var _hmt = _hmt || [];
      (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?204fcf6777f8efa834fe7c45a2336bf1";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();
    </script>
  </body>
</html>