ruby/config/routes.rb
require 'domain_constraint'
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints DomainConstraint.new('career', 'career-source', 'career-dev') do
    root to: 'career#index'
    get '/social',         to: 'career#social'
    get '/school',         to: 'career#school'
    get '/position/:id',   to: 'career#position', as: :position
  end

  constraints DomainConstraint.new('blog', 'blog-source', 'blog-dev') do
    root to: 'blog#index'
    get '/archives/all',                to: 'blog#all'
    get '/archives/:id',                to: 'blog#archives', as: :archives
    get '/archives/author/:author',     to: 'blog#author',   as: :archives_author
    get '/archives/category/:category', to: 'blog#category', as: :archives_category
  end

  scope "(:locale)", locale: /en/ do
    root to: 'welcome#index'
    get '/products/kodo',                          to: 'products#kodo'
    get '/products/kodo/goglobal',                 to: 'products#kodo_goglobal'
    get '/products/pili',                          to: 'products#pili'
    get '/products/sdk',                           to: 'products#sdk'
    get '/products/rtn',                           to: 'products#rtn'
    get '/products/pandora',                       to: 'products#pandora'
    get '/products/insight',                       to: 'products#insight'
    get '/products/express',                       to: 'products#express'
    get '/products/censor',                        to: 'products#censor'
    get '/products/fusion',                        to: 'products#fusion'
    get '/products/qcdn',                          to: 'products#qcdn'
    get '/products/dora',                          to: 'products#dora'
    get '/products/kirk',                          to: 'products#kirk'
    get '/products/vance',                         to: 'products#vance'
    get '/products/atlab',                         to: 'products#atlab'
    get '/products/plsv',                          to: 'products#plsv'
    get '/products/vcs',                           to: 'products#vcs'
    get '/products/player',                        to: 'products#player'
    get '/products/newmedia',                      to: 'products#newmedia'
    get '/products/newmedia/playout',              to: 'products#playout'
    get '/products/newmedia/mam',                  to: 'products#mam'
    get '/products/newmedia/convergence',          to: 'products#convergence'
    get '/products/newmedia/cms',                  to: 'products#cms'
    get '/products/newmedia/operation',            to: 'products#operation'
    get '/products/newmedia/live',                 to: 'products#live'
    # 超级分辨率下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/resolution',           to: 'products#resolution'
    get '/products/newmedia/demolition',           to: 'products#demolition'
    # 业务微服务引擎下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/microservices',        to: 'products#microservices'
    get '/products/newmedia/editor',               to: 'products#editor'
    # 数据可视化下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/visualization',        to: 'products#visualization'
    get '/products/newmedia/interact',             to: 'products#interact'
    get '/products/newmedia/auditor',              to: 'products#auditor'
    get '/products/newmedia/copyright',            to: 'products#copyright'
    get '/products/pili/livequiz',                 to: 'products#livequiz'
    get '/products/qavs',                          to: 'products#qavs'
    get '/products/qvm',                           to: 'products#qvm'
    get '/products/qvm/partner',                   to: 'products#qvm_partner'
    get '/products/qvm-company',                   to: 'products#qvm_company'
    get '/products/edu',                           to: 'products#edu'
    get '/products/ess',                           to: 'products#ess'
    get '/products/snow',                          to: 'products#snow'
    get '/products/ecs',                           to: 'products#ecs'
    get '/products/private-cloud-kodo',            to: 'products#kodoprivate'
    get '/products/private-cloud-kodo/company',    to: 'products#kodoprivate_company'
    get '/products/linking',                       to: 'products#linking'
    get '/products/sms',                           to: 'products#sms'
    get '/products/svesdk',                        to: 'products#svesdk'

    # 推广结束，屏蔽 qvmfeeds 和 censorfeeds 的路由
    # https://jira.qiniu.io/browse/BO-5919
    # qvm 广告推广页
    # get '/products/qvmfeeds',       to: 'products#qvmfeeds'
    # censor 广告推广页
    # get '/products/censorfeeds',    to: 'products#censorfeeds'

    # censor 新增的两个页面，用于关键词排名，只增加路由不新增入口
    # https://jira.qiniu.io/browse/BO-5767
    get '/products/censor/photo',   to: 'products#censor_photo'
    get '/products/censor/video',   to: 'products#censor_video'

    get '/contact',                to: 'welcome#contact'
    get '/solutions',              to: 'welcome#solution'
    get '/news',                   to: 'welcome#news'
    get '/product_news',           to: 'welcome#product_news'
    get '/welfares',               to: 'welcome#welfares'
    get '/company',                to: 'welcome#company'
    get '/case',                   to: 'welcome#case'
    get '/user-agreement',         to: 'welcome#user_agreement'
    get '/sdk-agreement',          to: 'welcome#sdk_agreement'
    get '/sla-kodo',               to: 'welcome#sla_kodo'
    get '/sla-kodo-old',           to: 'welcome#sla_kodo_old'
    get '/sla-kodo-new',           to: 'welcome#sla_kodo_new'
    get '/sla-fusion',             to: 'welcome#sla_fusion'
    get '/sla-fusion-old',         to: 'welcome#sla_fusion_old'
    get '/sla-fusion-new',         to: 'welcome#sla_fusion_new'
    get '/sla-pili',               to: 'welcome#sla_pili'
    get '/sla-dora',               to: 'welcome#sla_dora'
    get '/sla-sms',                to: 'welcome#sla_sms'
    get '/sla-qvm',                to: 'welcome#sla_qvm'
    get '/privacy-right',          to: 'welcome#privacy_right'
    # get '/goglobal',               to: 'welcome#goglobal'
    # get '/alaccelerator',          to: 'welcome#alaccelerator'
    get '/cdnprice2018',           to: 'welcome#cdnprice2018'
    get '/invite',                 to: 'welcome#invite'
    get '/ssl',                    to: 'welcome#ssl'
    get '/partner',                to: 'welcome#partner'

    get '/solutions/kodoe',                        to: 'solutions#kodoe'

    resources :resources, only: [] do
      collection do
        get 'plup'
      end
    end

    # userinfo
    get '/userinfo', to: 'userinfo#userinfo'

    resources 'events', only: [:index] do
      collection do
        get 'tech_online', 'ecug', 'niushow', 'arch', 'ecugcon', 'free', 'qvm1rmb', 'qvm0rmb', 'double11', 'qvm2for3', 'activity'
      end
    end

    # 获取动态 banner
    get '/banner/dynamic', to: 'welcome#get_dynamic_banner'
    # 获取动态广告位
    get '/advert/dynamic', to: 'welcome#get_dynamic_advert'

    # 1024 活动页定位到 events#event1024
    get '/events/1024event', to: 'events#event1024'
    # 限时 cdn 流量包活动页面路由
    get '/events/cdn-package', to: 'events#cdn_package'
    # cdn + 短视频活动页面路由
    get '/events/fusion-package', to: 'events#fusion_package'
    # dora 转码时长包活动
    get '/events/dora-package', to: 'events#dora_package'
    # qvm 燃情一夏活动
    get '/events/qvmsumsale', to: 'events#qvmsumsale'
    # dora 促销活动
    get '/events/dora-avsmart', to: 'events#dora_avsmart'
    # qvmsumsale 10 点开抢限制
    get '/events/qvmsumsale/is_start', to: 'events#qvmsumsale_is_start'
    # 2019 年 618 活动
    # https://jira.qiniu.io/browse/BO-7519
    get '/events/2019618', to: 'events#big_promotion'
    # 2019 年 618 活动是否结束
    get '/events/2019618/is_end', to: 'events#is_big_promotion_end'
    # 2019 年 1024 活动
    # https://jira.qiniu.io/browse/BO-9137
    get '/events/20191024', to: 'events#zelda'
    # 2019 年 1024 活动是否结束
    get '/events/20191024/is_end', to: 'events#is_zelda_end'
    # 2019 年 1111 活动
    get '/events/20191111', to: 'events#double11_2019'
    # 2019 年 1111 活动是否结束
    get '/events/20191111/is_end', to: 'events#is_double11_2019_end'
    # 2019 年 1111 活动 dora 领券
    post '/events/20191111/dora/voucher', to: 'events#double11_2019_dora_voucher'
    # 2019 年 1212 活动
    get '/events/20191212', to: 'events#double12_2019'
    # 2019 年 1212 活动是否结束
    get '/events/20191212/is_end', to: 'events#is_double12_2019_end'
    # 2019 年 1212 活动组合包预约功能
    get '/events/20191212/combo/order', to: 'events#double12_2019_combo_order'
    # 购买套餐包
    post '/events/package/buy', to: 'events#package_buy'
    # 2020 年春季采购活动
    get '/events/20200316', to: 'events#spring_sale'
    # 2020 年春季采购活动是否结束
    get '/events/20200316/is_end', to: 'events#is_spring_sale_end'
    # 获取分享链接
    get '/get_share_link', to: 'events#get_share_link'
    # 获取用户邀请信息
    get '/get_invited_info', to: 'events#get_invited_info'
    # 获取 1024 活动是否过期
    get '/get_expired', to: 'events#get_expired'
    # 创建 1024 活动抽奖资格
    post '/event1024_create_award', to: 'events#event1024_create_award'

    # 抗击 2019-nCoV 活动
    get '/events/fighting-2019-ncov', to: 'events#fighting_ncov'

    # img_censor
    post '/img_censor', to: 'products#img_censor'

    # video_censor
    post '/video_censor', to: 'products#video_censor'

    # 根据 jobID 获取视频审核结果
    post '/video_censor_result', to: 'products#video_censor_result'

    # 获取 censor 产品页 今日审核总量 和 今日已封禁违规内容 数据
    get '/censor_quantity_data', to: 'products#censor_quantity_data'

    # qvm
    post "/qvm/user/action", to: 'products#report_user_action'

    # get_heat
    get '/get_heat', to: 'events#get_heat'

    resources 'prices', only: [:index]
    # https://jira.qiniu.io/browse/BO-6267
    # caculator 路由改为 calculator, caculator_qvm 路由改为 calculator_qvm
    # 为了防止现有的路由 404，因此不关闭现有路由

ruby/app/controllers/blog_controller.rb
class BlogController < ApplicationController
  layout "blog"

  before_action :getHot

  def index
    @title = "博客"
    # @q = Archive.ransack(title_or_summary_cont: params[:q])
    # @archives = @q.result.page params[:page]
    redirect_to(:action => 'category', :category => '5')
  end

  def all
    @title = "博客"
    # @q = Archive.ransack(title_or_summary_cont: params[:q])
    # 根据 current_editor 判断查询条件
    if current_editor.nil? == false
      @q = Archive.where(status: ['published', 'offline', 'draft']).ransack(title_or_summary_cont: params[:q])
    else
      @q = Archive.where(status: 'published').ransack(title_or_summary_cont: params[:q])
    end
    @archives = @q.result.page params[:page]
    render "index"
  end

  def archives
    # @archive = Archive.find(params[:id])
    # 根据 current_editor 判断查询条件
    if current_editor.nil? == false
      @archive = Archive.where(status: ['published', 'offline', 'draft']).find(params[:id])
    else
      @archive = Archive.where(status: 'published').find(params[:id])
    end
    @title = @archive[:title]
  end

  def author
    # @archives = Archive.where(author: params[:author]).page params[:page]
    # 根据 current_editor 判断查询条件
    if current_editor.nil? == false
      @archives = Archive.where(status: ['published', 'offline', 'draft'], author: params[:author]).page params[:page]
    else
      @archives = Archive.where(status: 'published', author: params[:author]).page params[:page]
    end
    @title = "博客"
    render "index"
  end

  def category
    category = params[:category]
    if category == "5"
      category = [5, 51, 52, 53, 54, 55, 56]
    end
    # @archives = Archive.where(category: category).page params[:page]
    # 根据 current_editor 判断查询条件
    if current_editor.nil? == false
      @archives = Archive.where(status: ['published', 'offline', 'draft'], category: category).page params[:page]
    else
      @archives = Archive.where(status: 'published', category: category).page params[:page]
    end
    @title = "博客"
    render "index"
  end

  private

    def getHot
      # @hot_archives = Archive.hot_archives
      # 根据 current_editor 判断查询条件
      if current_editor.nil? == false
        @hot_archives = Archive.where(status: ['published', 'offline', 'draft']).hot_archives
      else
        @hot_archives = Archive.where(status: 'published').hot_archives
      end
    end

end

ruby/app/views/blog/_sidebar.html.erb
<div class="sidebar">
  <form class="searchform" method="get" action="<%= archives_all_path %>">
    <input type="text" name="q" class="field" placeholder="Search" id="blog-search-input">
    <input type="submit" class="submit">
  </form>

  <div class="sidebar-content">
    <div class="cat-item cat-item-first">
      <% if is_1024event_on() -%>
      <a href="https://www.qiniu.com/events/1024event?hmsr=blog&hmpl=AD-blog&hmcu=1024event&hmkw=&hmci=" title="云采购狂欢季" target="_blank">
        <%= image_tag "blog/1024event.jpg", width: "100%", class: "m-b-sm" -%>
      </a>
      <% else -%>
      <a href="https://www.qiniu.com/events/free?hmsr=blog&hmpl=AD-blog&hmcu=free&hmkw=&hmci=" title="免费云服务套餐" target="_blank">
        <%= image_tag "blog/mianfeiyunfuwu.jpg", width: "100%", class: "m-b-sm" -%>
      </a>
      <% end -%>
      <a href="https://www.qiniu.com/events/qvm0rmb?hmsr=blog&hmpl=AD-blog&hmcu=qvm0rmb&hmkw=&hmci=" title="0 元主机" target="_blank">
        <%= image_tag "blog/qvm0rmb.jpg", width: "100%" -%>
      </a>
    </div>

    <div class="cat-item hot-clicks">
      <div class="title">热文推荐</div>
      <ul class="hot-clicks-wrapper">
        <% @hot_archives.each do |archive| %>
          <li><%= link_to archive.title, archives_path(id: archive.id), class: "hot-title" -%></li>
        <% end %>
      </ul>
    </div>
    <ul class="list list-blog">
      <li class="cat-item all-articles">
        <%= link_to "所有文章", archives_all_path, class: "category" -%>
      </li>
      <li class="cat-item all-news">
        <%= link_to "新闻动态", archives_category_path(category: Archive::CATEGORIES.key("新闻动态")), class: "category" -%>
      </li>
      <li class="cat-item all-products">
        <%= link_to "产品动态", archives_category_path(category: Archive::CATEGORIES.key("产品动态")), class: "category" -%>
      </li>
      <li class="cat-item all-cases">
        <%= link_to "客户案例", archives_category_path(category: Archive::CATEGORIES.key("客户案例")), class: "category" -%>
      </li>
      <li class="cat-item all-bennefits">
        <%= link_to "近期福利", archives_category_path(category: Archive::CATEGORIES.key("近期福利")), class: "category" -%>
      </li>
      <li class="cat-item all-skills active">
        <%= link_to "技术实践", archives_category_path(category: Archive::CATEGORIES.key("技术实践")), class: "category" -%>
      </li>
      <li class="cat-item all-comics">
        <%= link_to "牛棚漫画", archives_category_path(category: Archive::CATEGORIES.key("牛棚漫画")), class: "category" -%>
      </li>
      <li class="cat-item all-hirings">
        <%= link_to "加入我们", archives_category_path(category: Archive::CATEGORIES.key("加入我们")), class: "category" -%>
      </li>
    </ul>
    <div class="cat-item cat-item-first">
      <%= image_tag "blog/wechat.png", alt: "公众号", width: "110px", class: "m-b-sm" -%>
      <p>关注七牛云公众号</p>
    </div>
  </div>
</div>

ruby/app/views/blog/archives.html.erb
<style>
  nav.navbar {
    background-color: #303848 !important;
  }
</style>
<div class="features features-blog container-blog">
  <div class="blog-nav-back"></div>
  <div class="container">
    <div class="row row-clear">
      <div class="col-sm-8">
        <div class="tapbar">
          <%= link_to '博客首页', '/archives/category/5', class: 'link' %>
          <%= link_to '所有文章', '/archives/all', class: 'link' %>
          <%= link_to '大数据', '/archives/category/51', class: 'link' %>
          <%= link_to '人工智能', '/archives/category/52', class: 'link' %>
          <%= link_to '容器云', '/archives/category/53', class: 'link' %>
          <%= link_to '基础设施', '/archives/category/54', class: 'link' %>
          <%= link_to '音视频', '/archives/category/55', class: 'link' %>
          <%= link_to 'Go 语言', '/archives/category/56', class: 'link' %>
        </div>
        <div class="blog-content m-b-xs">
          <div class="entry-header">
            <div class="entry-title">
              <a href="javascript:;" class="title"><%= @archive[:title] %></a>
            </div>
            <div class="entry-meta">
              <span class="entry-meta-unit entry-author">
                <%= image_tag "blog/icon-zuozhe.png", class:"img", alt: "作者" -%>
                <%= link_to @archive[:author], archives_author_path(author: @archive[:author]) -%>
              </span>
              <span class="entry-meta-unit entry-date">
                <%= image_tag "blog/icon-riqi.png", class:"img", alt: "日期" -%>
                <a href="javascript:;">
                  <%= @archive[:created_at].strftime("%Y-%m-%d") %>
                </a>
              </span>
              <span class="entry-meta-unit entry-utility-prep">
                <%= image_tag "blog/icon-fabu.png", class:"img", alt: "发布" -%>
                <span>发布在</span>
                <%= link_to Archive::CATEGORIES[@archive[:category]], archives_category_path(category: @archive[:category]) -%>
              </span>
              <!--
              <span class="entry-meta-unit page-views">
                <%= image_tag "blog/icon-liulanliang.png", class:"img", alt: "浏览量" -%>
                <span class="entry-utility-prep">
                  浏览量
                </span>
                <span class="entry-utility-prep">
                  2128
                </span>
              </span>
              -->
            </div>
          </div>
          <div class="blog-html"><%= raw @archive[:content] %></div>
        </div>
        <!-- social-share-button BEGIN -->
        <%= social_share_button_tag('#分享#' + @archive[:title]) %>
        <!-- social-share-button END -->
      </div>
      <div class="col-sm-4 side-mbbar-wrapper">
        <%= render :partial => "sidebar" %>
      </div>
    </div>
  </div>
</div>

ruby/app/views/blog/index.html.erb
<div class="jumbotron hero blog-banner">
  <div class="container">
    <div class="middle-container">
      <div class="row">
        <div class="col-xs-7 banner-title">
          <h3>七牛直播云</br>一站式直播解决方案</h3>
          <h4>快速搭建完整的视频直播系统</h4>
          <div class="actions">
            <%= link_to "立即搭建", "https://www.qiniu.com/products/pili?hmsr=blog&hmpl=AD-blog&hmcu=pili&hmkw=&hmci=",target: "_blank", class: "btn btn-lg btn-default m-r m-b-xs" -%>
          </div>
        </div>
        <div class="col-xs-5 hidden-xs">
          <div class="right-mask-banner">
            <%= image_tag "banner/banner-pili-right-zh.png", alt: "pili", width: '90%' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="features features-blog container-blog">
  <div class="container">
    <div class="row row-clear">
      <div class="col-sm-8">
        <div class="tapbar">
          <%= link_to '所有文章', '/archives/all', class: 'link' %>
          <%= link_to '大数据', '/archives/category/51', class: 'link' %>
          <%= link_to '人工智能', '/archives/category/52', class: 'link' %>
          <%= link_to '容器云', '/archives/category/53', class: 'link' %>
          <%= link_to '基础设施', '/archives/category/54', class: 'link' %>
          <%= link_to '音视频', '/archives/category/55', class: 'link' %>
          <%= link_to 'Go 语言', '/archives/category/56', class: 'link' %>
        </div>
        <% @archives.each do |archive| %>
          <div class="row">
            <div class="blog-content">
              <% if archive.cover? %><div class="col-sm-8">
              <% else %><div class="col-sm-12"><% end %>
                <div class="entry-header">
                  <div class="entry-title">
                    <%= link_to archive.title, archives_path(id: archive.id), class: "title" -%>
                  </div>
                  <% if archive.cover? %>
                    <div class="blog-text"><%= truncate(archive.summary, length: 70) %></div>
                  <% else %>
                    <div class="blog-text"><%= truncate(archive.summary, length: 100) %></div>
                  <% end %>
                  
                  <div class="entry-meta">
                    <span class="entry-meta-unit entry-author">
                      <%= image_tag "blog/icon-zuozhe.png", class:"img", alt: "作者" -%>
                      <%= link_to archive.author, archives_author_path(author: archive.author) -%>
                    </span>
                    <span class="entry-meta-unit entry-date">
                      <%= image_tag "blog/icon-riqi.png", class:"img", alt: "日期" -%>
                      <a href="">
                        <%=archive.created_at.strftime("%Y-%m-%d") %>
                      </a>
                    </span>
                    <span class="entry-meta-unit entry-utility-prep">
                      <%= image_tag "blog/icon-fabu.png", class:"img", alt: "发布" -%>
                      <span>发布在</span>
                      <%= link_to Archive::CATEGORIES[archive.category], archives_category_path(category: archive.category) -%>
                    </span>
                    <!--
                    <span class="entry-meta-unit page-views">
                      <%= image_tag "blog/icon-liulanliang.png", class:"img", alt: "浏览量" -%>
                      <span class="entry-utility-prep">
                        浏览量
                      </span>
                      <span class="entry-utility-prep">
                        2128
                      </span>
                    </span>
                    -->
                  </div>
                </div>
              </div>
              <% if archive.cover? %>
                <div class="col-sm-4">
                  <div class="blog-imgBox">
                    <img src=<%=archive.cover %>>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <div class="paginate-wrapper"><%= paginate @archives, window: 2, outer_window: 3 %></div>
      </div>
      <div class="col-sm-4 side-mbbar-wrapper">
        <%= render :partial => "sidebar" %>
      </div>
    </div>
  </div>
</div>