ruby/config/routes.rb
require 'domain_constraint'
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints DomainConstraint.new('career', 'career-source', 'career-dev') do
    root to: 'career#index'
    get '/social',         to: 'career#social'
    get '/school',         to: 'career#school'
    get '/position/:id',   to: 'career#position', as: :position
  end

  constraints DomainConstraint.new('blog', 'blog-source', 'blog-dev') do
    root to: 'blog#index'
    get '/archives/all',                to: 'blog#all'
    get '/archives/:id',                to: 'blog#archives', as: :archives
    get '/archives/author/:author',     to: 'blog#author',   as: :archives_author
    get '/archives/category/:category', to: 'blog#category', as: :archives_category
  end

  scope "(:locale)", locale: /en/ do
    root to: 'welcome#index'
    get '/products/kodo',                          to: 'products#kodo'
    get '/products/kodo/goglobal',                 to: 'products#kodo_goglobal'
    get '/products/pili',                          to: 'products#pili'
    get '/products/sdk',                           to: 'products#sdk'
    get '/products/rtn',                           to: 'products#rtn'
    get '/products/pandora',                       to: 'products#pandora'
    get '/products/insight',                       to: 'products#insight'
    get '/products/express',                       to: 'products#express'
    get '/products/censor',                        to: 'products#censor'
    get '/products/fusion',                        to: 'products#fusion'
    get '/products/qcdn',                          to: 'products#qcdn'
    get '/products/dora',                          to: 'products#dora'
    get '/products/kirk',                          to: 'products#kirk'
    get '/products/vance',                         to: 'products#vance'
    get '/products/atlab',                         to: 'products#atlab'
    get '/products/plsv',                          to: 'products#plsv'
    get '/products/vcs',                           to: 'products#vcs'
    get '/products/player',                        to: 'products#player'
    get '/products/newmedia',                      to: 'products#newmedia'
    get '/products/newmedia/playout',              to: 'products#playout'
    get '/products/newmedia/mam',                  to: 'products#mam'
    get '/products/newmedia/convergence',          to: 'products#convergence'
    get '/products/newmedia/cms',                  to: 'products#cms'
    get '/products/newmedia/operation',            to: 'products#operation'
    get '/products/newmedia/live',                 to: 'products#live'
    # 超级分辨率下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/resolution',           to: 'products#resolution'
    get '/products/newmedia/demolition',           to: 'products#demolition'
    # 业务微服务引擎下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/microservices',        to: 'products#microservices'
    get '/products/newmedia/editor',               to: 'products#editor'
    # 数据可视化下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/visualization',        to: 'products#visualization'
    get '/products/newmedia/interact',             to: 'products#interact'
    get '/products/newmedia/auditor',              to: 'products#auditor'
    get '/products/newmedia/copyright',            to: 'products#copyright'
    get '/products/pili/livequiz',                 to: 'products#livequiz'
    get '/products/qavs',                          to: 'products#qavs'
    get '/products/qvm',                           to: 'products#qvm'
    get '/products/qvm/partner',                   to: 'products#qvm_partner'
    get '/products/qvm-company',                   to: 'products#qvm_company'
    get '/products/edu',                           to: 'products#edu'
    get '/products/ess',                           to: 'products#ess'
    get '/products/snow',                          to: 'products#snow'
    get '/products/ecs',                           to: 'products#ecs'
    get '/products/private-cloud-kodo',            to: 'products#kodoprivate'
    get '/products/private-cloud-kodo/company',    to: 'products#kodoprivate_company'
    get '/products/linking',                       to: 'products#linking'
    get '/products/sms',                           to: 'products#sms'
    get '/products/svesdk',                        to: 'products#svesdk'

    # 推广结束，屏蔽 qvmfeeds 和 censorfeeds 的路由
    # https://jira.qiniu.io/browse/BO-5919
    # qvm 广告推广页
    # get '/products/qvmfeeds',       to: 'products#qvmfeeds'
    # censor 广告推广页
    # get '/products/censorfeeds',    to: 'products#censorfeeds'

    # censor 新增的两个页面，用于关键词排名，只增加路由不新增入口
    # https://jira.qiniu.io/browse/BO-5767
    get '/products/censor/photo',   to: 'products#censor_photo'
    get '/products/censor/video',   to: 'products#censor_video'

    get '/contact',                to: 'welcome#contact'
    get '/solutions',              to: 'welcome#solution'
    get '/news',                   to: 'welcome#news'
    get '/product_news',           to: 'welcome#product_news'
    get '/welfares',               to: 'welcome#welfares'
    get '/company',                to: 'welcome#company'
    get '/case',                   to: 'welcome#case'
    get '/user-agreement',         to: 'welcome#user_agreement'
    get '/sdk-agreement',          to: 'welcome#sdk_agreement'
    get '/sla-kodo',               to: 'welcome#sla_kodo'
    get '/sla-kodo-old',           to: 'welcome#sla_kodo_old'
    get '/sla-kodo-new',           to: 'welcome#sla_kodo_new'
    get '/sla-fusion',             to: 'welcome#sla_fusion'
    get '/sla-fusion-old',         to: 'welcome#sla_fusion_old'
    get '/sla-fusion-new',         to: 'welcome#sla_fusion_new'
    get '/sla-pili',               to: 'welcome#sla_pili'
    get '/sla-dora',               to: 'welcome#sla_dora'
    get '/sla-sms',                to: 'welcome#sla_sms'
    get '/sla-qvm',                to: 'welcome#sla_qvm'
    get '/privacy-right',          to: 'welcome#privacy_right'
    # get '/goglobal',               to: 'welcome#goglobal'
    # get '/alaccelerator',          to: 'welcome#alaccelerator'
    get '/cdnprice2018',           to: 'welcome#cdnprice2018'
    get '/invite',                 to: 'welcome#invite'
    get '/ssl',                    to: 'welcome#ssl'
    get '/partner',                to: 'welcome#partner'

    get '/solutions/kodoe',                        to: 'solutions#kodoe'

    resources :resources, only: [] do
      collection do
        get 'plup'
      end
    end

    # userinfo
    get '/userinfo', to: 'userinfo#userinfo'

    resources 'events', only: [:index] do
      collection do
        get 'tech_online', 'ecug', 'niushow', 'arch', 'ecugcon', 'free', 'qvm1rmb', 'qvm0rmb', 'double11', 'qvm2for3', 'activity'
      end
    end

    # 获取动态 banner
    get '/banner/dynamic', to: 'welcome#get_dynamic_banner'
    # 获取动态广告位
    get '/advert/dynamic', to: 'welcome#get_dynamic_advert'

    # 1024 活动页定位到 events#event1024
    get '/events/1024event', to: 'events#event1024'
    # 限时 cdn 流量包活动页面路由
    get '/events/cdn-package', to: 'events#cdn_package'
    # cdn + 短视频活动页面路由
    get '/events/fusion-package', to: 'events#fusion_package'
    # dora 转码时长包活动
    get '/events/dora-package', to: 'events#dora_package'
    # qvm 燃情一夏活动
    get '/events/qvmsumsale', to: 'events#qvmsumsale'
    # dora 促销活动
    get '/events/dora-avsmart', to: 'events#dora_avsmart'
    # qvmsumsale 10 点开抢限制
    get '/events/qvmsumsale/is_start', to: 'events#qvmsumsale_is_start'
    # 2019 年 618 活动
    # https://jira.qiniu.io/browse/BO-7519
    get '/events/2019618', to: 'events#big_promotion'
    # 2019 年 618 活动是否结束
    get '/events/2019618/is_end', to: 'events#is_big_promotion_end'
    # 2019 年 1024 活动
    # https://jira.qiniu.io/browse/BO-9137
    get '/events/20191024', to: 'events#zelda'
    # 2019 年 1024 活动是否结束
    get '/events/20191024/is_end', to: 'events#is_zelda_end'
    # 2019 年 1111 活动
    get '/events/20191111', to: 'events#double11_2019'
    # 2019 年 1111 活动是否结束
    get '/events/20191111/is_end', to: 'events#is_double11_2019_end'
    # 2019 年 1111 活动 dora 领券
    post '/events/20191111/dora/voucher', to: 'events#double11_2019_dora_voucher'
    # 2019 年 1212 活动
    get '/events/20191212', to: 'events#double12_2019'
    # 2019 年 1212 活动是否结束
    get '/events/20191212/is_end', to: 'events#is_double12_2019_end'
    # 2019 年 1212 活动组合包预约功能
    get '/events/20191212/combo/order', to: 'events#double12_2019_combo_order'
    # 购买套餐包
    post '/events/package/buy', to: 'events#package_buy'
    # 2020 年春季采购活动
    get '/events/20200316', to: 'events#spring_sale'
    # 2020 年春季采购活动是否结束
    get '/events/20200316/is_end', to: 'events#is_spring_sale_end'
    # 获取分享链接
    get '/get_share_link', to: 'events#get_share_link'
    # 获取用户邀请信息
    get '/get_invited_info', to: 'events#get_invited_info'
    # 获取 1024 活动是否过期
    get '/get_expired', to: 'events#get_expired'
    # 创建 1024 活动抽奖资格
    post '/event1024_create_award', to: 'events#event1024_create_award'

    # 抗击 2019-nCoV 活动
    get '/events/fighting-2019-ncov', to: 'events#fighting_ncov'

    # img_censor
    post '/img_censor', to: 'products#img_censor'

    # video_censor
    post '/video_censor', to: 'products#video_censor'

    # 根据 jobID 获取视频审核结果
    post '/video_censor_result', to: 'products#video_censor_result'

    # 获取 censor 产品页 今日审核总量 和 今日已封禁违规内容 数据
    get '/censor_quantity_data', to: 'products#censor_quantity_data'

    # qvm
    post "/qvm/user/action", to: 'products#report_user_action'

    # get_heat
    get '/get_heat', to: 'events#get_heat'

    resources 'prices', only: [:index]
    # https://jira.qiniu.io/browse/BO-6267
    # caculator 路由改为 calculator, caculator_qvm 路由改为 calculator_qvm
    # 为了防止现有的路由 404，因此不关闭现有路由

ruby/app/controllers/welcome_controller.rb
require "uri"
require 'net/http'
require 'json'

class WelcomeController < ApplicationController

  def index
    # @top_archives = Archive.top_archives
    # 根据 current_editor 判断查询条件
    # index 首页不查找数据库获取文章
    # if current_editor.nil? == false
    #   @top_archives = Archive.where(status: ['published', 'offline', 'draft']).top_archives
    # else
    #   @top_archives = Archive.where(status: 'published').top_archives
    # end
  end

  def get_dynamic_banner
    marketing_host = Rails.configuration.marketing_host
    if marketing_host.blank? || marketing_host.nil?
      render json: {
        "is_success": false,
        "data": []
      }
      return
    end

    # banner 只显示 10 个
    req_uri = marketing_host + "/api/proxy/lego/banners-online?location=1&page=1&page_size=10"
    res = get_remote_data(req_uri)
    if res.nil? == false &&
       res["data"].nil? == false &&
       res["data"]["banners"].nil? == false
      render json: {
        "is_success": true,
        "data": res["data"]["banners"] || []
      }
      return
    end

    render json: {
      "is_success": false,
      "data": []
    }
    return
  end

  def get_dynamic_advert
    marketing_host = Rails.configuration.marketing_host
    if marketing_host.blank? || marketing_host.nil?
      render json: {
        "is_success": false,
        "data": []
      }
      return
    end

    # 广告位只显示 5 个
    req_uri = marketing_host + "/api/proxy/lego/adverts-online?page=1&page_size=5"
    res = get_remote_data(req_uri)
    if res.nil? == false &&
       res["data"].nil? == false &&
       res["data"]["adverts"].nil? == false
      render json: {
        "is_success": true,
        "data": res["data"]["adverts"] || []
      }
      return
    end

    render json: {
      "is_success": false,
      "data": []
    }
    return
  end

  def contact
  end

  def solution
  end

  def alaccelerator
  end

  def cdnprice2018
  end

  def news
    # @archives = Archive.news_archives
    # 根据 current_editor 判断查询条件
    if current_editor.nil? == false
      @archives = Archive.where(status: ['published', 'offline', 'draft']).news_archives.page params[:page]
    else
      @archives = Archive.where(status: 'published').news_archives.page params[:page]
    end
    render "about"
  end

  def product_news
    # @archives = Archive.product_archives
    # 根据 current_editor 判断查询条件
    if current_editor.nil? == false
      @archives = Archive.where(status: ['published', 'offline', 'draft']).product_archives.page params[:page]
    else
      @archives = Archive.where(status: 'published').product_archives.page params[:page]
    end
    render "about"
  end

  def welfares
    # @archives = Archive.welfares_archives
    # 根据 current_editor 判断查询条件
    if current_editor.nil? == false
      @archives = Archive.where(status: ['published', 'offline', 'draft']).welfares_archives.page params[:page]
    else
      @archives = Archive.where(status: 'published').welfares_archives.page params[:page]
    end
    render "about"
  end

  def company
  end

  def case
  end

  def user_agreement
    render "sla"
  end

  def sdk_agreement
    render "sla"
  end

  def sla_kodo
    render "sla"
  end

  def sla_kodo_old
    render "sla"
  end

  def sla_kodo_new
    # 考虑到 /sla-kodo-new 这个路由已经开放出去了
    # 重定向到 /sla-kodo
    redirect_to(Rails.configuration.www_host + "/sla-kodo", :status => 301)
  end

  def sla_fusion
    render "sla"
  end

  def sla_fusion_old
    render "sla"
  end

  def sla_fusion_new
    # 重定向到 /sla-fusion
    redirect_to(Rails.configuration.www_host + "/sla-fusion", :status => 301)
  end

  def sla_pili
    render "sla"
  end

  def sla_dora
    render "sla"
  end

  def sla_sms
    render "sla"
  end

  def sla_qvm
    render "sla"
  end

  def privacy_right
    render "sla"
  end

  def goglobal
    render "goglobal"
  end

  def invitation
    render "invitation"
  end

  def ssl
    render "ssl"
  end

  def partner
  end

  # remote get 请求
  def get_remote_data(req_uri)
    uri = URI.parse(req_uri)
    req = Net::HTTP::Get.new(uri)
    req["Content-Type"] = "application/json"

    begin
      http = Net::HTTP.new(uri.hostname, uri.port)
      if uri.port == 443
        http.use_ssl = true
      end
      res = http.request(req)
    rescue
      return nil
    end

    case res
      when Net::HTTPSuccess
        JSON.parse res.body
      else
        puts res.message
        return nil
    end
  end

  def robots
    if request.host == "www.qiniu.com"
      render plain: """\
        User-agent: *
      """
    else
      render plain: """\
        User-agent: Baiduspider
        Disallow: /
        User-agent: Sosospider
        Disallow: /
        User-agent: sogou spider
        Disallow: /
        User-agent: YodaoBot
        Disallow: /
        User-agent: Googlebot
        Disallow: /
        User-agent: Bingbot
        Disallow: /
        User-agent: Slurp
        Disallow: /
        User-agent: MSNBot
        Disallow: /
        User-agent: googlebot-image
        Disallow: /
        User-agent: googlebot-mobile
        Disallow: /
        User-agent: yahoo-blogs/v3.9
        Disallow: /
        User-agent: psbot
        Disallow: /
        User-agent: *
        Disallow: /\
      """
    end
  end

end

ruby/app/helpers/welcome_helper.rb
module WelcomeHelper

  # 校验welcome/index页面 top_archives 发布信息字段
  def index_archive_publish_meta(archive)
    "#{ archive[:created_at].strftime("%Y-%m-%d") } 发布在 #{ Archive::CATEGORIES[archive.category] || "" }"
  end

  # 校验welcome/about页面 archives 发布信息字段
  def about_archive_publish_meta(archive)
    "发布在 #{ Archive::CATEGORIES[archive.category] || "" }"
  end
end

ruby/app/views/welcome/about.html.erb
<div class="features features-about">
  <div class="container">
    <div class="row">
      <div class="col-sm-2">
        <ul class="nav nav-stacked left-tab" id="about-left-bar">
          <li class="active"><%= link_to "公司介绍", company_path -%></li>
          <li class="news"><%= link_to "新闻动态", news_path -%></li>
          <li class="product_news"><%= link_to "产品动态", product_news_path -%></li>
          <li class="welfares"><%= link_to "近期福利", welfares_path -%></li>
          <li><%= link_to "客户案例", case_path -%></li>
          <li><%= link_to "市场合作", cooperations_path -%></li>
          <li><%= link_to "加入我们", "http://career.qiniu.com/" -%></li>
          <li><%= link_to "联系我们", contact_path -%></li>
        </ul>
      </div>

      <div class="col-sm-10">
        <div class="sections-wrapper">
          <section id=<%= action_name -%>>
            <% @archives.each do |archive| %>
              <div class="news-modal clear-pt">
                <a href="<%= "#{ Rails.application.config.blog_host }/archives/#{ archive.id }" -%>" target="_blank">
                  <h4><%= archive[:title] -%></h4>
                  <time><%= archive[:created_at].strftime("%Y-%m-%d") -%></time>
                  <span class="category"><%= about_archive_publish_meta(archive) -%></span>
                  <p class="news-content"><%= archive[:summary] -%></p>
                </a>
              </div>
              <%# <%= content_tag :div, link_to(content_tag(:h4, archive[:title]) + content_tag(:time, archive[:created_at].strftime("%Y-%m-%d")) + content_tag(:span, "发布在   " + Archive::CATEGORIES[archive.category], class: "category") + content_tag(:p, archive[:summary], class: "news-content"), "#{ Rails.application.config.blog_host }/archives/#{ archive.id }", target: "_blank" ), class: "news-modal clear-pt" -%>
            <% end %>
            <div class="paginate-wrapper"><%= paginate @archives, window: 2, outer_window: 3 %></div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

ruby/app/views/welcome/goglobal.html.erb
<div class="jumbotron hero hero-goglobal">

</div>

<div class="features">
  <div class="container bottom-line">
    <div class="intro">
      <h3 class="text-left">七牛云出海创业扶持计划</h3>
    </div>
    <p class="m-b-md">中国互联网企业出海的十年编年史中，我们经历了安全工具大战、桌面大战，从 2016 开始，已来到了内容出海年。如今，更多创业者的野心从中国扩展到了全球， 在这个全球市场的争夺战中，谁能找准新动向，用高效的执行力占领市场？</p>
    <p class="m-b-md">作为国内领先云服务商，七牛云陪伴了 70 多万家优秀企业的成长，其中不乏许多出海的企业。本次出海扶持计划广泛整合出海相关产品和服务资源，共同助力创业者占领全球市场。</p>
    <p class="m-b-0">助力对象：</p>
    <p class="m-b-md">有明确出海需求的互联网产品，包括但不限于工具类、游戏类、直播、短视频等。</p>
    <p class="m-b-0">扶持内容：</p>
    <p class="m-b-0">1.七牛云联合合作伙伴准备的扶持计划礼包，覆盖技术、招聘、咨询、培训、团队协作等。</p>
    <p>2.加入有成功出海经验的出海社群，为您对接潜在人脉、市场。</p>
  </div>
</div>

<div class="features p-t-0">
  <div class="container bottom-line p-t-md">
    <div class="intro">
      <h3 class="text-left">如何申请七牛云出海创业扶持计划礼包？</h3>
    </div>
    <div class="text-center">
      <ul class="ul-step">
        <li class="step-li step-li-first">
          <div class="step-no">1</div>
          <p class="step-info text-left">立即申请，提交资料</p>
        </li>

        <li class="step-li">
          <div class="step-no">2</div>
          <p class="step-info text-left">等待资料审核（7个工作日）</p>
          <%= link_to "立刻申请", "https://jinshuju.net/f/NjYedm", target: "_blank", class: "step-submit-btn btn btn-primary color-light b-0" -%>
        </li>

        <li class="step-li step-li-no">
          <div class="step-no">3</div>
          <p class="step-info text-left">通过审核后，礼包发放</p>
        </li>
      </ul>
    </div>
    <div class="f-xs">
      <p>备注：</p>
      <p>1.「七牛云出海创业扶持计划」不可与七牛其他扶持计划同时申请；</p>
      <p>2. 礼包限量 100 份</p>
    </div>
  </div>
</div>

<div class="features p-t-0">
  <div class="container">
    <div class="intro">
      <h3 class="text-left">七牛云出海扶持计划礼包</h3>
    </div>
    <div class="p-t-md">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4 col-clear p-1">
          <div class="thumbnail b-2 p-relative">
            <div class="middle text-center">
              <%= image_tag "goglobal/libao-tutu.png", alt: "pic", width: 150 %>
              <div class="caption text-center">
                <p>1）图片 SDK 基础版、高级版：八折优惠</p>
                <p>2）视频特效 SDK：八折优惠</p>
                <p>3）人脸识别 SDK：八折优惠</p>
              </div>
            </div>
            <div class="cover">
              <p>涂图 TUTUCLOUD 是一家专注于视频图像处理技术的高科技企业。核心成员由 PPTV、华为、虹软等资深研发人员构成，拥有十五年以上的视频图像处理、识别研发经验。公司拥有完整的视频图像处理、分析解决方案，基于自研算法和深度神经网络开发的图像检测、识别、跟踪、处理算法已达到国际先进水平，可以为各行各业提供专业高效的视频图像处理、分析服务。</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-clear p-1">
          <div class="thumbnail b-2 p-relative">
            <div class="middle text-center">
              <%= image_tag "goglobal/libao-qiniu.png", alt: "pic", width: 150 %>
              <div class="caption text-center">
                <p>1）价值 3000 元的全球 CDN 代金券，有效期一年</p>
                <p>2）短视频、直播SDK 商用版免费一年</p>
              </div>
            </div>
            <div class="cover">
              <p>七牛云（隶属于上海七牛信息技术有限公司）是国内领先的企业级云服务商，专注于以数据管理为中心的云计算业务研发和运营，围绕富媒体场景推出了对象存储、CDN 加速、容器计算云、大数据平台、人工智能平台等产品，并提供一站式视频云解决方案。公司目前已位列国内云计算行业第一阵营，为 70 多万家企业提供服务。</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-clear p-1">
          <div class="thumbnail b-2 p-relative">
            <div class="middle text-center">
              <%= image_tag "goglobal/libao-moxtra.png", alt: "pic", width: 150 %>
              <div class="caption text-center">
                <p>购买 Moxtra 商业版本享受原价的八折优惠</p>
              </div>
            </div>
            <div class="cover">
              <p>Moxtra 由思科前 WebEx 创始人 CEO 和前协作首席工程师创立于旧金山，致力于提供协作解决方案涵盖了 SDK &amp; API 。 Moxtra 提供的 SDK 和 API 涵盖了即时通讯、音视频会议、电子白板、文件预览、桌面共享控制等，覆盖了全客户端。</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-clear p-1">
          <div class="thumbnail b-2 p-relative">
            <div class="middle text-center">
              <%= image_tag "goglobal/libao-heishi.png", alt: "pic", width: 150 %>
              <div class="caption text-center">
                <p>出海服务咨询，培训，资源对接九折优惠</p>
              </div>
            </div>
            <div class="cover">
              <p>全球知名的增长黑客与广告投放优化师垂直社群</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-clear p-1">
          <div class="thumbnail b-2 p-relative">
            <div class="middle text-center">
              <%= image_tag "goglobal/libao-nDefender.png", alt: "pic", width: 150 %>
              <div class="caption text-center">
                <p>价值 2 万元的企业信息安全云免费试用三个月</p>
              </div>
            </div>
            <div class="cover">
              <p>nDefender 云盾安全云，为国内企业量身定制轻量级企业信息安全云，隶属于跨国互联网集团 Dotc United Group，拥有雄厚的国际技术资源，致力于在原有安全技术基础上，有效融合大数据、机器学习、安全可视化等技术，提供形态灵活的安全产品，保障客户业务安全。</p>
            </div>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-clear p-1">
          <div class="thumbnail b-2 p-relative">
            <div class="middle text-center">
              <%= image_tag "goglobal/libao-zhirenshe.png", alt: "pic", width: 150 %>
              <div class="caption text-center">
                <p>职人社为 C 轮以上公司提供服务费九折的招聘服务</p>
              </div>
            </div>
            <div class="cover">
              <p>职人社为 C 轮以上公司提供服务费 9 折的招聘服务。职人社是一家致力于优质人才招聘的服务公司，有丰富海外市场、黑客增长专业人才。</p>
            </div>
          </div>
        </div>
      </div>
      <div class="pull-right">
        <%= link_to "如何加入扶持计划礼包？", "https://jinshuju.net/forms/auE7X2", target: "_blank", class: "more" -%>
      </div>
    </div>
  </div>
</div>

<div class="features p-t-0">
  <div class="container">
    <div class="intro">
      <h3 class="text-left">推荐产品</h3>
    </div>
    <div class="row">
      <div class="col-sm-6"><%= link_to image_tag("goglobal/tuijianchanpin-duanshipin.jpg"), products_plsv_path %></div>
      <div class="col-sm-6"><%= link_to image_tag("goglobal/tuijianchanpin-zhiboyun.jpg"), products_pili_path %></div>
    </div>
  </div>
</div>

<div class="features p-t-0">
  <div class="container">
    <div class="intro">
      <h3 class="text-left">推荐活动</h3>
    </div>
    <div class="row">
      <div class="col-sm-6"><%= link_to image_tag("goglobal/tuijianhuodong.jpg"), "https://0x7.me/Xb20", target: "_blank" %></div>
    </div>
  </div>
</div>

<div class="features p-t-0">
  <div class="container">
    <div class="intro">
      <h3 class="text-left">合作伙伴</h3>
    </div>
    <div class="row">
      <div class="col-xs-3 col-sm-2 col-md-2"><%= image_tag "goglobal/hezuohuoban-daguanziben.png", alt: "pic" %></div>
      <div class="col-xs-3 col-sm-2 col-md-2"><%= image_tag "goglobal/hezuohuoban-heishi.png", alt: "pic" %></div>
    </div>
  </div>
</div>

<div class="features p-t-0">
  <div class="container">
    <div class="intro">
      <h3 class="text-left">合作媒体</h3>
    </div>
    <div class="row">
      <div class="col-xs-3 col-sm-2 col-md-2"><%= image_tag "goglobal/hezuomeiti-chuangtoutiao.png", alt: "pic" %></div>
      <div class="col-xs-3 col-sm-2 col-md-2"><%= image_tag "goglobal/hezuomeiti-huxiu.png", alt: "pic" %></div>
      <div class="col-xs-3 col-sm-2 col-md-2"><%= image_tag "goglobal/hezuomeiti-itjuzi.png", alt: "pic" %></div>
      <div class="col-xs-3 col-sm-2 col-md-2"><%= image_tag "goglobal/hezuomeiti-RTBmeiti.png", alt: "pic" %></div>
      <div class="col-xs-3 col-sm-2 col-md-2"><%= image_tag "goglobal/hezuomeiti-xinjingji100.png", alt: "pic" %></div>
      <div class="col-xs-3 col-sm-2 col-md-2"><%= image_tag "goglobal/hezuomeiti-zhudao.png", alt: "pic" %></div>
    </div>
  </div>
</div>