ruby/config/routes.rb
require 'domain_constraint'
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  constraints DomainConstraint.new('career', 'career-source', 'career-dev') do
    root to: 'career#index'
    get '/social',         to: 'career#social'
    get '/school',         to: 'career#school'
    get '/position/:id',   to: 'career#position', as: :position
  end

  constraints DomainConstraint.new('blog', 'blog-source', 'blog-dev') do
    root to: 'blog#index'
    get '/archives/all',                to: 'blog#all'
    get '/archives/:id',                to: 'blog#archives', as: :archives
    get '/archives/author/:author',     to: 'blog#author',   as: :archives_author
    get '/archives/category/:category', to: 'blog#category', as: :archives_category
  end

  scope "(:locale)", locale: /en/ do
    root to: 'welcome#index'
    get '/products/kodo',                          to: 'products#kodo'
    get '/products/kodo/goglobal',                 to: 'products#kodo_goglobal'
    get '/products/pili',                          to: 'products#pili'
    get '/products/sdk',                           to: 'products#sdk'
    get '/products/rtn',                           to: 'products#rtn'
    get '/products/pandora',                       to: 'products#pandora'
    get '/products/insight',                       to: 'products#insight'
    get '/products/express',                       to: 'products#express'
    get '/products/censor',                        to: 'products#censor'
    get '/products/fusion',                        to: 'products#fusion'
    get '/products/qcdn',                          to: 'products#qcdn'
    get '/products/dora',                          to: 'products#dora'
    get '/products/kirk',                          to: 'products#kirk'
    get '/products/vance',                         to: 'products#vance'
    get '/products/atlab',                         to: 'products#atlab'
    get '/products/plsv',                          to: 'products#plsv'
    get '/products/vcs',                           to: 'products#vcs'
    get '/products/player',                        to: 'products#player'
    get '/products/newmedia',                      to: 'products#newmedia'
    get '/products/newmedia/playout',              to: 'products#playout'
    get '/products/newmedia/mam',                  to: 'products#mam'
    get '/products/newmedia/convergence',          to: 'products#convergence'
    get '/products/newmedia/cms',                  to: 'products#cms'
    get '/products/newmedia/operation',            to: 'products#operation'
    get '/products/newmedia/live',                 to: 'products#live'
    # 超级分辨率下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/resolution',           to: 'products#resolution'
    get '/products/newmedia/demolition',           to: 'products#demolition'
    # 业务微服务引擎下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/microservices',        to: 'products#microservices'
    get '/products/newmedia/editor',               to: 'products#editor'
    # 数据可视化下线，去掉路由
    # https://jira.qiniu.io/browse/BO-7148
    # get '/products/newmedia/visualization',        to: 'products#visualization'
    get '/products/newmedia/interact',             to: 'products#interact'
    get '/products/newmedia/auditor',              to: 'products#auditor'
    get '/products/newmedia/copyright',            to: 'products#copyright'
    get '/products/pili/livequiz',                 to: 'products#livequiz'
    get '/products/qavs',                          to: 'products#qavs'
    get '/products/qvm',                           to: 'products#qvm'
    get '/products/qvm/partner',                   to: 'products#qvm_partner'
    get '/products/qvm-company',                   to: 'products#qvm_company'
    get '/products/edu',                           to: 'products#edu'
    get '/products/ess',                           to: 'products#ess'
    get '/products/snow',                          to: 'products#snow'
    get '/products/ecs',                           to: 'products#ecs'
    get '/products/private-cloud-kodo',            to: 'products#kodoprivate'
    get '/products/private-cloud-kodo/company',    to: 'products#kodoprivate_company'
    get '/products/linking',                       to: 'products#linking'
    get '/products/sms',                           to: 'products#sms'
    get '/products/svesdk',                        to: 'products#svesdk'

    # 推广结束，屏蔽 qvmfeeds 和 censorfeeds 的路由
    # https://jira.qiniu.io/browse/BO-5919
    # qvm 广告推广页
    # get '/products/qvmfeeds',       to: 'products#qvmfeeds'
    # censor 广告推广页
    # get '/products/censorfeeds',    to: 'products#censorfeeds'

    # censor 新增的两个页面，用于关键词排名，只增加路由不新增入口
    # https://jira.qiniu.io/browse/BO-5767
    get '/products/censor/photo',   to: 'products#censor_photo'
    get '/products/censor/video',   to: 'products#censor_video'

    get '/contact',                to: 'welcome#contact'
    get '/solutions',              to: 'welcome#solution'
    get '/news',                   to: 'welcome#news'
    get '/product_news',           to: 'welcome#product_news'
    get '/welfares',               to: 'welcome#welfares'
    get '/company',                to: 'welcome#company'
    get '/case',                   to: 'welcome#case'
    get '/user-agreement',         to: 'welcome#user_agreement'
    get '/sdk-agreement',          to: 'welcome#sdk_agreement'
    get '/sla-kodo',               to: 'welcome#sla_kodo'
    get '/sla-kodo-old',           to: 'welcome#sla_kodo_old'
    get '/sla-kodo-new',           to: 'welcome#sla_kodo_new'
    get '/sla-fusion',             to: 'welcome#sla_fusion'
    get '/sla-fusion-old',         to: 'welcome#sla_fusion_old'
    get '/sla-fusion-new',         to: 'welcome#sla_fusion_new'
    get '/sla-pili',               to: 'welcome#sla_pili'
    get '/sla-dora',               to: 'welcome#sla_dora'
    get '/sla-sms',                to: 'welcome#sla_sms'
    get '/sla-qvm',                to: 'welcome#sla_qvm'
    get '/privacy-right',          to: 'welcome#privacy_right'
    # get '/goglobal',               to: 'welcome#goglobal'
    # get '/alaccelerator',          to: 'welcome#alaccelerator'
    get '/cdnprice2018',           to: 'welcome#cdnprice2018'
    get '/invite',                 to: 'welcome#invite'
    get '/ssl',                    to: 'welcome#ssl'
    get '/partner',                to: 'welcome#partner'

    get '/solutions/kodoe',                        to: 'solutions#kodoe'

    resources :resources, only: [] do
      collection do
        get 'plup'
      end
    end

    # userinfo
    get '/userinfo', to: 'userinfo#userinfo'

    resources 'events', only: [:index] do
      collection do
        get 'tech_online', 'ecug', 'niushow', 'arch', 'ecugcon', 'free', 'qvm1rmb', 'qvm0rmb', 'double11', 'qvm2for3', 'activity'
      end
    end

    # 获取动态 banner
    get '/banner/dynamic', to: 'welcome#get_dynamic_banner'
    # 获取动态广告位
    get '/advert/dynamic', to: 'welcome#get_dynamic_advert'

    # 1024 活动页定位到 events#event1024
    get '/events/1024event', to: 'events#event1024'
    # 限时 cdn 流量包活动页面路由
    get '/events/cdn-package', to: 'events#cdn_package'
    # cdn + 短视频活动页面路由
    get '/events/fusion-package', to: 'events#fusion_package'
    # dora 转码时长包活动
    get '/events/dora-package', to: 'events#dora_package'
    # qvm 燃情一夏活动
    get '/events/qvmsumsale', to: 'events#qvmsumsale'
    # dora 促销活动
    get '/events/dora-avsmart', to: 'events#dora_avsmart'
    # qvmsumsale 10 点开抢限制
    get '/events/qvmsumsale/is_start', to: 'events#qvmsumsale_is_start'
    # 2019 年 618 活动
    # https://jira.qiniu.io/browse/BO-7519
    get '/events/2019618', to: 'events#big_promotion'
    # 2019 年 618 活动是否结束
    get '/events/2019618/is_end', to: 'events#is_big_promotion_end'
    # 2019 年 1024 活动
    # https://jira.qiniu.io/browse/BO-9137
    get '/events/20191024', to: 'events#zelda'
    # 2019 年 1024 活动是否结束
    get '/events/20191024/is_end', to: 'events#is_zelda_end'
    # 2019 年 1111 活动
    get '/events/20191111', to: 'events#double11_2019'
    # 2019 年 1111 活动是否结束
    get '/events/20191111/is_end', to: 'events#is_double11_2019_end'
    # 2019 年 1111 活动 dora 领券
    post '/events/20191111/dora/voucher', to: 'events#double11_2019_dora_voucher'
    # 2019 年 1212 活动
    get '/events/20191212', to: 'events#double12_2019'
    # 2019 年 1212 活动是否结束
    get '/events/20191212/is_end', to: 'events#is_double12_2019_end'
    # 2019 年 1212 活动组合包预约功能
    get '/events/20191212/combo/order', to: 'events#double12_2019_combo_order'
    # 购买套餐包
    post '/events/package/buy', to: 'events#package_buy'
    # 2020 年春季采购活动
    get '/events/20200316', to: 'events#spring_sale'
    # 2020 年春季采购活动是否结束
    get '/events/20200316/is_end', to: 'events#is_spring_sale_end'
    # 获取分享链接
    get '/get_share_link', to: 'events#get_share_link'
    # 获取用户邀请信息
    get '/get_invited_info', to: 'events#get_invited_info'
    # 获取 1024 活动是否过期
    get '/get_expired', to: 'events#get_expired'
    # 创建 1024 活动抽奖资格
    post '/event1024_create_award', to: 'events#event1024_create_award'

    # 抗击 2019-nCoV 活动
    get '/events/fighting-2019-ncov', to: 'events#fighting_ncov'

    # img_censor
    post '/img_censor', to: 'products#img_censor'

    # video_censor
    post '/video_censor', to: 'products#video_censor'

    # 根据 jobID 获取视频审核结果
    post '/video_censor_result', to: 'products#video_censor_result'

    # 获取 censor 产品页 今日审核总量 和 今日已封禁违规内容 数据
    get '/censor_quantity_data', to: 'products#censor_quantity_data'

    # qvm
    post "/qvm/user/action", to: 'products#report_user_action'

    # get_heat
    get '/get_heat', to: 'events#get_heat'

    resources 'prices', only: [:index]
    # https://jira.qiniu.io/browse/BO-6267
    # caculator 路由改为 calculator, caculator_qvm 路由改为 calculator_qvm
    # 为了防止现有的路由 404，因此不关闭现有路由

ruby/app/helpers/products_helper.rb
module ProductsHelper
end

ruby/app/views/products/censorfeeds.html.erb
<div class="jumbotron hero hero-censorfeeds censorfeeds-bg">
  <div class="container">
    <div class="middle-container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <h1>明瞳图片鉴黄</h1>
          <p>违规内容一扫而光</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="features features-censorfeeds-demo censorfeeds-bg">
  <div class="container">
    <div class="row">
      <%# title %>
      <div class="col-xs-12 col-sm-12 col-md-12 col-title">
        <p class="demo-title">AI 鉴黄体验区</p>
      </div>

      <%# 主图像 %>
      <div class="col-xs-12 col-sm-12 col-md-12 col-main-img">
        <div class="image-censorfeeds-main" id="image-censorfeeds-main">
          <%= image_tag "censorfeeds/icon-zhengchang.png", class: "icon-censorfeeds-result icon-zhengchang", id: "icon-censorfeeds-zhengchang", width: 100 -%>
          <%= image_tag "censorfeeds/icon-xinggan.png", class: "icon-censorfeeds-result icon-xinggan", id: "icon-censorfeeds-xinggan", width: 100 -%>
          <%= image_tag "censorfeeds/icon-weigui.png", class: "icon-censorfeeds-result icon-weigui", id: "icon-censorfeeds-weigui", width: 100 -%>
        </div>
      </div>

      <%# 三个选择图像 %>
      <div class="col-xs-4 col-sm-4 col-md-4 col-select-img">
        <div class="image-censorfeeds-select image-1 selected" id="image-censorfeeds-1"></div>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-select-img">
        <div class="image-censorfeeds-select image-2" id="image-censorfeeds-2"></div>
      </div>
      <div class="col-xs-4 col-sm-4 col-md-4 col-select-img">
        <div class="image-censorfeeds-select image-3" id="image-censorfeeds-3"></div>
      </div>

      <%# 输入 url %>
      <div class="col-xs-12 col-sm-12 col-md-12 col-url-input">
        <div class="input-group">
          <input type="text" class="form-control input-censorfeeds" placeholder="输入图片 URL">
          <span class="input-group-btn">
            <div class="btn btn-primary btn-lg btn-censorfeeds btn-detection" id="censorfeeds-detection-btn" type="button">检测</div>
          </span>
        </div>
      </div>

      <%# 立即咨询 %>
      <div class="col-xs-12 col-sm-12 col-md-12 col-consult">
        <%= link_to "立即咨询", "https://jinshuju.net/f/pRS9oF?ref=www.qiniu.com/products/censorfeeds", class: "btn btn-primary btn-lg btn-censorfeeds btn-consult", id: "btn-censorfeeds-consult", target: "_blank" -%>
      </div>

      <%# 两句文案 %>
      <div class="col-xs-12 col-sm-12 col-md-12 col-words">
        <p><span class="strong">0</span>&nbsp;<span class="color">风险</span>安全运营</p>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-words col-bottom">
        <p><span class="strong">18</span>&nbsp;<span class="color">万次</span>免费额度</p>
      </div>
    </div>
  </div>
</div>

ruby/app/views/products/fusion.html.erb
<div class="jumbotron hero hero-fusion">
  <div class="container">
    <div class="middle-container">
      <div class="row">
        <div class="col-sm-8 col-xs-12">
          <h2><%= I18n.t("views.products.fusion.banner.title") %></h2>
          <p><%= I18n.t("views.products.fusion.banner.desc") %></p>
          <div class="actions <%= I18n.t("views.language") != 'zh' ? 'd-none' : '' %>">
            <%= link_to "立即使用", signup_url(), target: "_blank", class: "btn btn-lg btn-default m-r m-b-xs fusion-banner-btn" -%>
            <%= link_to "产品价格", prices_path + "?source=fusion", class: "btn btn-lg btn-hollow m-b-xs" -%>
            <h5><%= link_to raw("域名型 DV SSL 证书免费申请 &gt;&gt;"), ssl_path, target: "_blank", class: "out_link" -%></h5>
            <h5 class="margin-l-negative">「 CDN 动态加速&nbsp;<%= link_to "立即使用", Rails.configuration.portal_host + "/cdn/domain/create?platform=dynamic&guideDynamic#platform", target: "_blank", class: "out_link", id: "fusion-page-employ" -%> 」</h5>
          </div>
        </div>
        <div class="col-sm-4 hidden-xs">
          <div class="right-mask-banner">
            <%= image_tag "banner/banner-cdn-right-zh.png", alt: "fusion", width: '100%' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="features-nav fusion-nav hidden-xs">
  <div class="container">
    <div class="tabs">
      <ul class="nav nav-tabs nav-justified navbar-wrapper-middle">
        <% I18n.t("views.products.fusion.middlebar").each do |linkbar| %>
          <li class="<%= linkbar[:class] %>"><%= link_to linkbar[:title], linkbar[:href] -%></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="features section tab-content-section-1">
  <div class="container">
    <div class="intro">
      <h2 class="title"><%= I18n.t("views.products.fusion.feature1.title") %></h2>
    </div>

    <div class="bottom-line" style="text-align: center;">
      <%= image_tag I18n.t("views.products.fusion.feature1.icon"), width: "80%" %>
    </div>
  </div>
</div>

<div class="features features-superiority tab-content-section-2">
  <div class="container">
    <div class="intro">
      <h2 class="title"><%= I18n.t("views.products.fusion.feature2.title") %></h2>
    </div>

    <div class="row">
      <% I18n.t("views.products.fusion.feature2.col").each do |col| %>
        <div class="col-sm-6 col-xs-12">
          <div class="media">
            <div class="media-left">
              <%= image_tag col[:icon], class: "media-object", alt: col[:title], width: 110 %></a>
            </div>
            <div class="media-body">
              <h4 class="media-heading"><%= col[:title] -%></h4>
              <p><%= col[:desc] -%></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="features features-fusion features-distribute feature-color tab-content-section-3">
  <div class="container">
    <div class="intro">
      <h2 class="title"><%= I18n.t("views.products.fusion.feature3.title") %></h2>
    </div>

    <div class="tabs">
      <ul class="nav nav-tabs nav-justified points-bar nav-short" role="tablist">
        <% I18n.t("views.products.fusion.feature3.middlebar").each do |linkbar| %>
          <li class="<%= linkbar[:class] %>">
            <%= link_to linkbar[:title], linkbar[:href], data:{toggle:"tab"} -%>
          </li>
        <% end %>
      </ul>
      <div class="tab-content">
        <% I18n.t("views.products.fusion.feature3.sections").each do |sec| %>
          <section id="<%= sec[:id] %>" class="<%= sec[:class] %>">
            <%= image_tag sec[:icon] %>
          </section>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="features features-fusion features-scene tab-content-section-4" id="products-fusion-scene">
  <div class="container bottom-line">
    <div class="intro">
      <h2 class="title"><%= I18n.t("views.products.fusion.feature4.title") %></h2>
    </div>

    <div class="tabs">
      <ul class="nav nav-tabs nav-justified points-bar nav-short" role="tablist">
        <% I18n.t("views.products.fusion.feature4.middlebar").each do |linkbar| %>
          <li class="<%= linkbar[:class] %>"><%= link_to linkbar[:title], linkbar[:href], data:{toggle:"tab"} -%></li>
        <% end %>
      </ul>
      <div class="tab-content">
        <% I18n.t("views.products.fusion.feature4.sections").each do |sec| %>
          <section id="<%= sec[:id] %>" class="<%= sec[:class] %>">
            <div class="media">
              <div class="media-left">
                <%= image_tag sec[:icon], class: "media-object img-left", alt: sec[:title] %>
              </div>

              <div class="media-body">
                <p>
                  <%= sec[:desc] -%>
                  <% if sec[:id] == "tab-usage-section-4" -%>
                  <%= link_to "立即使用", Rails.configuration.portal_host + "/cdn/domain/create?platform=dynamic&guideDynamic#platform", target: "_blank", class: "more", id: "fusion-scene-employ" -%>
                  <% end -%>
                </p>
              </div>
            </div>
          </section>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="features features-less tab-content-section-5">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-2">
        <h2 class="title"><%= I18n.t("views.products.fusion.feature5.title") %></h2>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-10">
        <div id="cases-slider" class="conveyor slick-slider draggable">
          <div><%= image_tag "client-zte-highlight@2x.jpg", alt: "中兴", title: "中兴", class: "case" %></div>
          <div><%= image_tag "fusion/client-momo.jpg", alt: "陌陌", title: "陌陌", class: "case" %></div>
          <div><%= image_tag "fusion/client-anxinzhengquan-highlight@2x.jpg", alt: "安信证券", title: "安信证券", class: "case" %></div>
          <div><%= image_tag "fusion/client-miaopai.jpg", alt: "秒拍", title: "秒拍", class: "case" %></div>
          <div><%= image_tag "fusion/client-mangguotv-highlight@2x.jpg", alt: "芒果TV", title: "芒果TV", class: "case" %></div>
          <div><%= image_tag "fusion/client-wifibanlv-highlight@2x.jpg", alt: "wifi伴侣", title: "wifi伴侣", class: "case" %></div>
          <div><%= image_tag "fusion/client-qichezhijia.jpg", alt: "汽车之家", title: "汽车之家", class: "case" %></div>
          <div><%= image_tag "fusion/client-tantan.jpg", alt: "探探", title: "探探", class: "case" %></div>
          <div><%= image_tag "fusion/client-kuaikan.jpg", alt: "快看", title: "快看", class: "case" %></div>
          <div><%= image_tag "client-yuekezaixianxuexi.jpg", alt: "粤科学习在线", title: "粤科学习在线", class: "case" %></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="features features-less feature-color tab-content-section-6 <%= I18n.t("views.language") != 'zh' ? 'd-none' : '' %>">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-2">
        <h2 class="title">产品相关</h2>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-10">
        <div class="row">
          <div class="col-sm-2 col-xs-6">
            <h4>常用文档</h4>
            <ul class="links-list">
              <li><%= link_to "快速入门", "https://developer.qiniu.com/fusion/manual/1228/fusion-quick-start", target: "_blank", title: "快速入门" -%></li>
              <li><%= link_to "DV 证书验证指南", "https://developer.qiniu.com/ssl/manual/3667/ssl-certificate-of-free-dns-validation-guide", target: "_blank", title: "DV 证书验证指南" -%></li>
              <li><%= link_to "七牛全球下载加速的海外一览表", "https://developer.qiniu.com/fusion/manual/1360/seven-cattle-download-speed-of-the-world-s-overseas-schedule", target: "_blank", title: "七牛全球下载加速的海外一览表" -%></li>
              <li><%= link_to "绑定加速域名和域名解析流程", "https://developer.qiniu.com/fusion/manual/1367/custom-domain-name-binding-process", target: "_blank", title: "绑定加速域名和域名解析流程" -%></li>
            </ul>
          </div>
          <div class="col-sm-2 col-xs-6">
            <h4>API 文档</h4>
            <ul class="links-list">
              <li><%= link_to "流量带宽", "https://developer.qiniu.com/fusion/api/1230/traffic-bandwidth", target: "_blank", title: "流量带宽" -%></li>
              <li><%= link_to "缓存刷新与查询", "https://developer.qiniu.com/fusion/api/1229/cache-refresh", target: "_blank", title: "缓存刷新与查询" -%></li>
              <li><%= link_to "文件预取与查询", "https://developer.qiniu.com/fusion/api/1227/file-prefetching", target: "_blank", title: "文件预取与查询" -%></li>
              <li><%= link_to "日志下载", "https://developer.qiniu.com/fusion/api/1226/download-the-log", target: "_blank", title: "日志下载" -%></li>
            </ul>
          </div>
          <div class="col-sm-3 col-xs-6">
            <h4>SDK 及工具</h4>
            <ul class="links-list">
              <li><%= link_to "CDN 日志查询", "https://developer.qiniu.com/fusion/tools/1665/qlogfetch", target: "_blank", title: "CDN 日志查询和下载工具" -%></li>
            </ul>
          </div>
          <div class="col-sm-2 col-xs-6">
            <h4>常见问题</h4>
            <ul class="links-list">
              <li><%= link_to "域名配置问题", "https://developer.qiniu.com/fusion/kb/1322/how-to-configure-cname-domain-name", target: "_blank", title: "域名配置问题" -%></li>
              <li><%= link_to "刷新缓存问题", "https://developer.qiniu.com/fusion/kb/3644/refresh-the-cache-fails-consistency-method-validation-file", target: "_blank", title: "刷新缓存问题" -%></li>
              <li><%= link_to "HTTPS 相关问题", "https://developer.qiniu.com/fusion/kb/3725/how-to-apply-for-and-use-free-certificate", target: "_blank", title: "HTTPS 相关问题" -%></li>
            </ul>
          </div>
          <div class="col-sm-3 col-xs-6">
            <h4>产品动态</h4>
            <ul class="links-list">
              <li><%= link_to "斩获 GFIC 2016 “产品创新奖”，七牛云 CDN 突围而出", "https://blog.qiniu.com/archives/7541", target: "_blank", title: "斩获 GFIC 2016 “产品创新奖”，七牛云 CDN 突围而出" -%></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

ruby/app/views/products/qvmfeeds.html.erb
<div class="jumbotron hero hero-qvmfeeds qvmfeeds-bg">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-hero">
        <%= image_tag "qvmfeeds/image-banner.png", class: "image-banner", width: "100%" -%>
        <%= image_tag "qvmfeeds/icon-red-packet.png", class: "icon-red-packet", alt: "3000 元云服务器抵用券", width: "90%" -%>
      </div>
    </div>
  </div>
</div>

<div class="features features-qvmfeeds-body qvmfeeds-bg">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-body-image">
        <%= image_tag "qvmfeeds/image-body.png", class: "image-body", width: "100%" -%>
      </div>
    </div>
    <div class="row row-operation">
      <div class="col-xs-12 col-sm-12 col-md-12 col-operation">
        <%= link_to "马上领取", "https://jinshuju.net/f/GoMRMG?ref=www.qiniu.com/products/qvmfeeds", class: "btn btn-danger btn-lg btn-qvmfeeds", id: "btn-qvmfeeds-get", target: "_blank" -%>
        <div class="rules-container">
          <%= image_tag "qvmfeeds/icon-coin.png", class: "icon-coin", width: 60 -%>
          <p>填写完整信息即可领取代金券</p>
          <p>每位用户限领一次，不限新老用户</p>
          <p>代金券将在一周内通过邮件形式发送</p>
        </div>
      </div>
    </div>
  </div>
</div>